apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-qzqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-qzqe
    app.kubernetes.io/part-of: second-application
  name: pacman-qzqe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-qzqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman-qzqe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/second-application/pacman-qzqe@sha256:bf434fdf5be786582b2b2208c8c06001538c6ee34e33dcc2cd63c88ae25f3547
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
