apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-qzqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-qzqe
    app.kubernetes.io/part-of: second-application
  name: pacman-qzqe
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: pacman-qzqe
status:
  loadBalancer: {}
