apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-qzqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-qzqe
    app.kubernetes.io/part-of: second-application
  name: pacman-qzqetav8
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pacman-qzqe
    weight: 100
status: {}
